<CameraScreen>:
    GridLayout:
        cols: 1
        padding: 8
        spacing: 8
        Camera:
            id: camera
            play: False
        Button:
            id: camera_button
            text: 'Start Camera'
            on_press: root.start()
        Button:
            text: 'Capture Photo'
            on_press: root.capture()

<RootWidget>
    CameraScreen:
        id: camera_screen
        name: 'camera_screen'